# Generated by Django 5.2.3 on 2025-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondepacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
