# Generated by Django 5.2.3 on 2025-11-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondepacientes', '0002_alter_paciente_dui'),
        ('gestiondepacientes', '0002_pacientetratamiento'),
    ]

    operations = [
    ]
