# Generated by Django 5.2.3 on 2025-10-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiondepacientes', '0001_initial'),
        ('gestionespecialistas', '0003_rename_area_especialista_especialidad_and_more'),
        ('gestiontratamientos', '0003_alter_tratamiento_costo_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionespecialistas.especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestiondepacientes.paciente')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestiontratamientos.tratamiento')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
