# Generated by Django 5.2.2 on 2025-06-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionempleadosespecialistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
