# Generated by Django 5.2.3 on 2025-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tratamiento',
            },
        ),
    ]
