# Generated by Django 5.2.3 on 2025-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontratamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='id_tratamiento',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
