# Generated by Django 5.2.3 on 2025-10-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontratamientos', '0002_remove_tratamiento_id_tratamiento_tratamiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='costo_referencia',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
