# Generated by Django 5.2.3 on 2025-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='08:00:00')),
                ('hora_cierre', models.TimeField(default='18:00:00')),
                ('intervalo_citas', models.IntegerField(choices=[(10, '10 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '60 minutos (1 hora)')], default=30)),
            ],
            options={
                'verbose_name_plural': 'Configuración de la Clínica',
            },
        ),
    ]
