# Generated by Django 5.2.3 on 2025-09-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionespecialistas', '0002_remove_especialista_id_especialista_id_especialista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='area',
            new_name='especialidad',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='id_especialista',
        ),
        migrations.AddField(
            model_name='especialista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
