# Generated by Django 5.2.3 on 2025-11-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_referencia', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tratamiento',
            },
        ),
    ]
