# Generated by Django 5.2.3 on 2025-10-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('gestiondepacientes', '0001_initial'),
        ('gestionespecialistas', '0003_rename_area_especialista_especialidad_and_more'),
        ('gestiontratamientos', '0003_alter_tratamiento_costo_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionespecialistas.especialista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondepacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiontratamientos.tratamiento'),
        ),
    ]
