# Generated by Django 5.2.3 on 2025-11-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclinica',
            name='dias_laborales',
            field=models.CharField(choices=[('0,1,2,3,4,5', 'Lunes a Sábado'), ('0,1,2,3,4', 'Lunes a Viernes'), ('0,1,2,3,4,5,6', 'Toda la semana')], default='0,1,2,3,4,5', max_length=20),
        ),
    ]
