# Generated by Django 5.2.3 on 2025-11-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionclinica_dias_laborales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionclinica',
            name='intervalo_citas',
            field=models.IntegerField(choices=[(10, '10 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=30),
        ),
    ]
