# Generated by Django 5.2.3 on 2025-09-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionespecialistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='id',
        ),
        migrations.AddField(
            model_name='especialista',
            name='id_especialista',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
